artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
<<<<<<< HEAD
  source_URL: https://drive.google.com/file/d/13YhEwSVr5Dpf-L0b1flBmzzGel-bdPtj/view?usp=sharing
=======
  source_URL: https://drive.google.com/file/d/14j2qhrnoItgbS-wXslOuVtEdvB4vCj8u/view?usp=sharing 
>>>>>>> a383f156462c216cfecdc56b364743e4c364b632
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5
<<<<<<< HEAD
  
=======
>>>>>>> a383f156462c216cfecdc56b364743e4c364b632

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5
